name: Build executables

on: [push]

env:
  VERSION: "5.0"

jobs:
  # in theory we can use build matrix, but it has some complications so I will just repeat here
  build-matrix:
    runs-on: macos-10.15
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, windows-2019, macos-10.15, macos-11, macos-12]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Build
      run: |
        . ./build_scripts/install_dependencies.sh ${{ matrix.os }}
        . ./build_scripts/build.sh ${{ matrix.os }}
    - name: Release
      uses: softprops/action-gh-release@v1
      # if: startsWith(github.ref, 'refs/tags/')
      with:
        draft: true
        files: | # ./photomosaic-maker-${{ env.VERSION }}-${{ matrix.version }}-x64-build.tar.gz
          ./dist/photomosaic-maker-${{ env.VERSION }}-${{ matrix.os }}-x64
          ./dist/photomosaic-maker-${{ env.VERSION }}-${{ matrix.os }}-x64.tar.gz