name: Build executables

on: [push]

jobs:
  build-windows:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: ["windows", "macos", "ubuntu"]
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: collage
        environment-file: environment.yml
        auto-activate-base: false
    - name: Build
      shell: bash -l {0}
      run: |
        . ./build_scripts/install_dependencies.sh ${{ matrix.os }}
        . ./build_scripts/build.sh ${{ matrix.os }}
    - name: Release
      uses: softprops/action-gh-release@v1
      # if: startsWith(github.ref, 'refs/tags/')
      with:
        draft: true
        files: |
          ./dist/photomosaic-maker-3.0-${{ matrix.os }}-x64.exe
          ./dist/photomosaic-maker-3.0-${{ matrix.os }}-x64.tar.gz