name: Build executables

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Build
      run: |
        ./build_scripts/install_dependencies.sh linux
        ./build_scripts/build.sh linux
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        draft: true
        files: |
          ./dist/photomosaic-maker-3.0-linux
          
  build-macos:
    runs-on: macos-10.15
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Build
      run: |
        ./build_scripts/install_dependencies.sh macos
        ./build_scripts/build.sh macos
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        draft: true
        files: |
          ./dist/photomosaic-maker-3.0-macos-x64
          

  build-windows:
    runs-on: windows-2019
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
      shell: bash
    - name: Build
      run: |
        ./build_scripts/install_dependencies.sh windows
        ./build_scripts/build.sh windows
      shell: bash
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        draft: true
        files: |
          ./dist/photomosaic-maker-3.0-windows-x64.exe
          